# site-settings.rb
SiteSetting.top_menu: "categories|latest|new|unread"
SiteSetting.desktop_category_page_style: "categories_only"
SiteSetting.mobile_category_page_style: "categories_only"
SiteSetting.default_dark_mode_color_scheme_id: "1"
SiteSetting.page_loading_indicator: "spinner"
SiteSetting.pending_users_reminder_delay_minutes: "5"
SiteSetting.min_password_length: "8"
SiteSetting.min_admin_password_length: "8"
SiteSetting.min_post_length: "5"
SiteSetting.min_first_post_length: "5"
SiteSetting.min_personal_message_post_length: "5"
SiteSetting.min_topic_title_length: "5"
SiteSetting.default_emoji_reactions: "+1|heart|tada|-1"
SiteSetting.default_invitee_trust_level: "0"
SiteSetting.navigation_menu: "header dropdown"
SiteSetting.default_navigation_menu_categories: "2|3|4"
SiteSetting.default_sidebar_switch_panel_position: "top"
SiteSetting.maximum_backups: "7"
SiteSetting.remove_older_backups: "7"
SiteSetting.backup_frequency: "1"
SiteSetting.backup_time_of_day: "16:00"
SiteSetting.include_thumbnails_in_backups: "true"
SiteSetting.default_email_digest_frequency: "1440"
SiteSetting.discourse_automation_enabled: "true"
SiteSetting.chat_allowed_groups: "1|2|11|-4"
SiteSetting.discourse_gamification_enabled: "true"
SiteSetting.scorable_categories: "4"
SiteSetting.like_given_score_value: "0"
SiteSetting.user_invited_score_value: "0"
SiteSetting.time_read_score_value: "0"
SiteSetting.post_read_score_value: "0"
SiteSetting.topic_created_score_value: "0"
SiteSetting.post_created_score_value: "5"
SiteSetting.flag_created_score_value: "0"
SiteSetting.day_visited_score_value: "0"
SiteSetting.reaction_received_score_value: "0"
SiteSetting.reaction_given_score_value: "0"
SiteSetting.chat_reaction_received_score_value: "0"
SiteSetting.chat_reaction_given_score_value: "0"
SiteSetting.chat_message_created_score_value: "0"
SiteSetting.post_voting_enabled: "true"
SiteSetting.flag_posts_voting_comments_allowed_groups: "1"
SiteSetting.discourse_reactions_enabled: "true"
SiteSetting.discourse_reactions_desaturated_reaction_panel: "true"
SiteSetting.discourse_reactions_like_sync_enabled: "false"
SiteSetting.show_who_marked_solved: "true"
SiteSetting.accept_all_solutions_allowed_groups: "1|2"
SiteSetting.title: "OpenBMC"
SiteSetting.contact_email: "David_Chou@jabil.com"
SiteSetting.site_description: "A community for developers and engineers working with OpenBMC firmware — collaborate, ask questions, and share your knowledge."
SiteSetting.short_site_description: "OpenBMC - The OpenBMC Firmware Community"
SiteSetting.notification_email: "noreply@workspace.chat-mail.uno"
# SiteSetting.site_contact_username: "T.B.D"
# SiteSetting.site_contact_group_name: "T.B.D"
# SiteSetting.company_name: "T.B.D"
# SiteSetting.governing_law: "T.B.D"
# SiteSetting.city_for_disputes: "T.B.D"
SiteSetting.login_required: "true"
SiteSetting.clean_up_inactive_users_after_days: "30"
SiteSetting.edit_history_visible_to_public: "true"
SiteSetting.log_mail_processing_failures: "true"
SiteSetting.invalidate_inactive_admin_email_after_days: "30"

# Add more settings as needed
puts "Settings applied successfully!"
